# Generated by Django 4.1.6 on 2023-02-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Товар')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('smartphones', 'Смартфоны'), ('food', 'Еда'), ('furniture', 'Мебель'), ('other', 'Разное')], default='other', max_length=50, verbose_name='Категория')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Остаток')),
                ('image', models.CharField(blank=True, max_length=3000, verbose_name='Ссылка на фото')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
